# Предложения
## Получить список предложений

GET http://localhost:3456/offers HTTP/1.1
Content-Type: application/json

###

## Получить список премиальных предложений в городе

GET http://localhost:3456/offers?city=Paris&premium=true HTTP/1.1
Content-Type: application/json

###

## Cоздать новое предложение

POST http://localhost:3456/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NjYzYWIzYWM2NjQ3YTM3MGY4OTg2ZCIsImVtYWlsIjoiY0BkLnJ1IiwibmFtZSI6IkRlYW4gV2luY2hlc3RlciIsImlhdCI6MTcxODE5ODgwNCwiZXhwIjoxNzE4MzcxNjA0fQ.6TpV6U4Jazjll13uScb9-vUiXUq58JoCk73nMvBct38

{
  "name": "Предложение 1",
  "description": "Описание предложения 1",
  "price": 2345,
  "city": "Paris",
  "housing": "hotel",
  "rooms": 1,
  "guests": 2,
  "previewUrl": "https://example.com/preview.jpg",
  "features": [
    "Baby seat",
    "Washer",
    "Towels",
    "Fridge"
  ],
  "premium": true,
  "images": [
    "https://example.com/image1.jpg",
    "https://example.com/image2.jpg",
    "https://example.com/image3.jpg",
    "https://example.com/image4.jpg",
    "https://example.com/image5.jpg",
    "https://example.com/image6.jpg"
  ],
  "coordinates": {
    "lat": 55.7558,
    "lng": 37.6176
  }
}

###

## Получить детализированное предложение

GET http://localhost:3456/offers/66523434115ea323dacecd68 HTTP/1.1
Content-Type: application/json

###

## Oбновить данные предложения

PUT http://localhost:3456/offers/66523434115ea323dacecd68 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NjYzYWIzYWM2NjQ3YTM3MGY4OTg2ZCIsImVtYWlsIjoiY0BkLnJ1IiwibmFtZSI6IkRlYW4gV2luY2hlc3RlciIsImlhdCI6MTcxODE5ODgwNCwiZXhwIjoxNzE4MzcxNjA0fQ.6TpV6U4Jazjll13uScb9-vUiXUq58JoCk73nMvBct38

{
  "price": 9999,
  "city": "Amsterdam",
  "housing": "apartment"
}

###

## Загрузить превью предложения

POST http://localhost:3456/offers/66523434115ea323dacecd68/preview  HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NjYzYWIzYWM2NjQ3YTM3MGY4OTg2ZCIsImVtYWlsIjoiY0BkLnJ1IiwibmFtZSI6IkRlYW4gV2luY2hlc3RlciIsImlhdCI6MTcxODE5ODgwNCwiZXhwIjoxNzE4MzcxNjA0fQ.6TpV6U4Jazjll13uScb9-vUiXUq58JoCk73nMvBct38

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewUrl"; filename="image.png"
Content-Type: image/jpeg

< /Users/anatoly/Desktop/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загрузить изображения предложения

POST http://localhost:3456/offers/66523434115ea323dacecd68/images  HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NjYzYWIzYWM2NjQ3YTM3MGY4OTg2ZCIsImVtYWlsIjoiY0BkLnJ1IiwibmFtZSI6IkRlYW4gV2luY2hlc3RlciIsImlhdCI6MTcxODE5ODgwNCwiZXhwIjoxNzE4MzcxNjA0fQ.6TpV6U4Jazjll13uScb9-vUiXUq58JoCk73nMvBct38

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image.png"
Content-Type: image/png

< /Users/anatoly/Desktop/image.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image.jpg"
Content-Type: image/jpeg

< /Users/anatoly/Desktop/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Удалить предложение

DELETE http://localhost:3456/offers/66523434115ea323dacecd66 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NjYzYWIzYWM2NjQ3YTM3MGY4OTg2ZCIsImVtYWlsIjoiY0BkLnJ1IiwibmFtZSI6IkRlYW4gV2luY2hlc3RlciIsImlhdCI6MTcxODE5ODgwNCwiZXhwIjoxNzE4MzcxNjA0fQ.6TpV6U4Jazjll13uScb9-vUiXUq58JoCk73nMvBct38

###
